# baseurl = "/"
baseURL = "https://tardigrade.io/blog"
languageCode = "en-us"
languageLang = "en"
title = "Homepage"

# Pagination
paginate = 9

[taxonomies]
  category = "categories"
  author = "authors"

	[[headers]]
	  for = "/*"
	  [headers.values]
	Access-Control-Allow-Origin = "*"
